[package]
name = "android_injected_glue"
version = "0.2.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
description = "Injected glue for the Android JNI"
repository = "https://github.com/tomaka/android-rs-glue"
